name: Docker Image CI
on:
  workflow_dispatch: {}
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/gitlab-ce-arm:latest
          cache-from : type=gha
          cache-to : type=gha,mode=max